#!/bin/bash
# Initial setup for litellm-docker-proxy with Cloudflare Access auth.
#
# What this does:
#   1. Checks required tools (docker, cloudflared)
#   2. Authenticates with Cloudflare Access for the target OpenCode URL
#   3. Generates the .env file with required keys
#   4. Generates the CA cert bundle (needed for corporate/WARP networks)
#
# Usage:
#   ./setup.sh
#   ./setup.sh --url https://llmapi.yourdomain.com

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TARGET_URL=""

# ── Parse args ───────────────────────────────────────────────────────────────
while [[ $# -gt 0 ]]; do
    case $1 in
        --url) TARGET_URL="$2"; shift 2 ;;
        --help)
            echo "Usage: $0 [--url <opencode-url>]"
            exit 0
            ;;
        *) echo "Unknown option: $1"; exit 1 ;;
    esac
done

echo -e "${BLUE}================================================${NC}"
echo -e "${BLUE}  LiteLLM Proxy — Cloudflare Access Setup      ${NC}"
echo -e "${BLUE}================================================${NC}"
echo ""

# ── Check requirements ───────────────────────────────────────────────────────
echo -e "${YELLOW}Checking requirements...${NC}"

for tool in docker python3; do
    if ! command -v "$tool" &>/dev/null; then
        echo -e "${RED}Error: $tool is not installed${NC}"
        exit 1
    fi
    echo -e "  ${GREEN}✓${NC} $tool"
done

if ! command -v cloudflared &>/dev/null; then
    echo -e "  ${YELLOW}⚠ cloudflared not found — install with: brew install cloudflared${NC}"
    echo -e "  ${YELLOW}  (needed for automatic token management)${NC}"
    HAS_CLOUDFLARED=false
else
    echo -e "  ${GREEN}✓${NC} cloudflared"
    HAS_CLOUDFLARED=true
fi
echo ""

# ── Resolve target URL ───────────────────────────────────────────────────────
if [ -z "$TARGET_URL" ] && [ -f "$SCRIPT_DIR/.env" ]; then
    TARGET_URL=$(grep -E '^API_BASE_URL=' "$SCRIPT_DIR/.env" | cut -d= -f2- | tr -d '"'"'" | head -1)
fi

if [ -z "$TARGET_URL" ]; then
    echo -e "${YELLOW}Enter the OpenCode API base URL (e.g. https://llmapi.yourdomain.com):${NC}"
    read -r TARGET_URL
fi

if [ -z "$TARGET_URL" ]; then
    echo -e "${RED}Error: URL is required${NC}"
    exit 1
fi

HOSTNAME=$(python3 -c "from urllib.parse import urlparse; print(urlparse('$TARGET_URL').hostname)")
echo -e "Target: ${BLUE}$TARGET_URL${NC}  (host: $HOSTNAME)"
echo ""

# ── Cloudflare Access auth ───────────────────────────────────────────────────
echo -e "${YELLOW}Authenticating with Cloudflare Access...${NC}"

if [ "$HAS_CLOUDFLARED" = true ]; then
    cloudflared access login "$TARGET_URL"
    TOKEN_FILE=$(ls -t "$HOME/.cloudflared/${HOSTNAME}-"*"-token" 2>/dev/null | head -1)
    if [ -n "$TOKEN_FILE" ]; then
        echo -e "${GREEN}✓ Token written to: $TOKEN_FILE${NC}"
        CF_TOKEN=$(cat "$TOKEN_FILE")
    else
        echo -e "${YELLOW}Token file not found, falling back to opencode auth...${NC}"
        opencode auth login "$TARGET_URL"
        TOKEN_FILE=$(ls -t "$HOME/.cloudflared/${HOSTNAME}-"*"-token" 2>/dev/null | head -1)
        [ -n "$TOKEN_FILE" ] && CF_TOKEN=$(cat "$TOKEN_FILE") || CF_TOKEN=""
    fi
else
    echo -e "${YELLOW}Using opencode auth login (cloudflared not installed)...${NC}"
    opencode auth login "$TARGET_URL"
    TOKEN_FILE=$(ls -t "$HOME/.cloudflared/${HOSTNAME}-"*"-token" 2>/dev/null | head -1)
    [ -n "$TOKEN_FILE" ] && CF_TOKEN=$(cat "$TOKEN_FILE") || CF_TOKEN=""
fi

if [ -z "$CF_TOKEN" ]; then
    echo -e "${YELLOW}Could not retrieve token automatically. You can set CF_ACCESS_TOKEN manually in .env${NC}"
fi
echo ""

# ── Generate .env ────────────────────────────────────────────────────────────
echo -e "${YELLOW}Generating .env file...${NC}"

if [ -f "$SCRIPT_DIR/.env" ]; then
    cp "$SCRIPT_DIR/.env" "$SCRIPT_DIR/.env.bak"
    echo -e "  Backed up existing .env → .env.bak"
fi

# Generate random keys
MASTER_KEY="sk-litellm-$(python3 -c 'import secrets; print(secrets.token_hex(16))')"
SALT_KEY="sk-litellm-$(python3 -c 'import secrets; print(secrets.token_hex(16))')"

cat > "$SCRIPT_DIR/.env" << EOF
# Generated by setup.sh on $(date)

# ── OpenCode API ──────────────────────────────────────────────────────────────
API_BASE_URL=$TARGET_URL

# ── Cloudflare Access Token ───────────────────────────────────────────────────
# The proxy reads ~/.cloudflared/${HOSTNAME}-*-token automatically.
# This env var is a fallback if the token file is not found.
# Refresh with: ./refresh-token.sh
CF_ACCESS_TOKEN=$CF_TOKEN

# ── LiteLLM ───────────────────────────────────────────────────────────────────
LITELLM_MASTER_KEY=$MASTER_KEY
LITELLM_SALT_KEY=$SALT_KEY
EOF

echo -e "${GREEN}✓ .env generated${NC}"
echo ""

# ── Generate CA bundle ───────────────────────────────────────────────────────
echo -e "${YELLOW}Generating CA bundle (cacert.pem)...${NC}"

if [ -f "$SCRIPT_DIR/cacert.pem" ]; then
    echo -e "  cacert.pem already exists, skipping"
else
    if [[ "$OSTYPE" == "darwin"* ]]; then
        security find-certificate -a -p /System/Library/Keychains/SystemRootCertificates.keychain \
            > "$SCRIPT_DIR/cacert.pem" 2>/dev/null
        echo -e "${GREEN}✓ cacert.pem generated from macOS keychain${NC}"
    elif [ -f /etc/ssl/certs/ca-certificates.crt ]; then
        cp /etc/ssl/certs/ca-certificates.crt "$SCRIPT_DIR/cacert.pem"
        echo -e "${GREEN}✓ cacert.pem copied from system${NC}"
    elif [ -f /etc/ssl/cert.pem ]; then
        cp /etc/ssl/cert.pem "$SCRIPT_DIR/cacert.pem"
        echo -e "${GREEN}✓ cacert.pem copied from system${NC}"
    else
        echo -e "${YELLOW}⚠ Could not find system CA bundle. Create cacert.pem manually.${NC}"
    fi
fi
echo ""

# ── Summary ──────────────────────────────────────────────────────────────────
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}  Setup complete!                               ${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo -e "  Target URL:   ${BLUE}$TARGET_URL${NC}"
echo -e "  Token file:   ~/.cloudflared/${HOSTNAME}-*-token"
echo ""
echo -e "${YELLOW}Next steps:${NC}"
echo ""
echo "  1. Start the stack:"
echo -e "     ${GREEN}docker compose up -d${NC}"
echo ""
echo "  2. Configure Claude Code:"
echo -e "     ${GREEN}export ANTHROPIC_BASE_URL=http://localhost:4000/v1${NC}"
echo -e "     ${GREEN}export ANTHROPIC_API_KEY=$MASTER_KEY${NC}"
echo ""
echo "  3. When your token expires, refresh without restarting:"
echo -e "     ${GREEN}./refresh-token.sh${NC}"
echo ""
